# Generated by Django 4.2 on 2023-05-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_carga_horario_evento_carga_horaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='dt_fim',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='dt_inicio',
            new_name='data_termino',
        ),
    ]
